spring:
  application:
    name: stock-report
  profiles:
    active: dev
  mongodb:
    uri: mongodb://localhost:27017/stockreport
  jackson:
    time-zone: Asia/Seoul

  threads:
    virtual:
      enabled: true

server:
  port: 8080

logging:
  level:
    com.stockreport: DEBUG

gemini:
  api-key: ${GEMINI_API_KEY:}

slack:
  webhook-url: ${SLACK_WEBHOOK_URL:}
